sudo: required
language: java
jdk:
- oraclejdk8
services:
  - docker
after_success:
- mvn cobertura:cobertura coveralls:report
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t maxdemarzi/neo_travis .
- docker push maxdemarzi/neo_travis:latest

